default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails6app_db
  username: postgres
  password: nopass
  host: localhost


production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
